In [1]:
import pandas as pd
import pymysql
from sqlalchemy import create_engine

In [5]:
engine = create_engine(
    "mysql+pymysql://root:2021HC0007@localhost/tennis_project"
)

print("Connected Successfully!")

Connected Successfully!

In [7]:
query = "SELECT * FROM Categories"

df = pd.read_sql(query, engine)

df

  category_id category_name
0        cat1           ATP
1        cat2           WTA
2        cat3       ITF Men
3        cat4     ITF Women

In [9]:
query = "SELECT * FROM Competitions"

df = pd.read_sql(query, engine)

df

  competition_id   competition_name parent_id     type gender category_id
0          comp1         ATP Finals      None  singles    men        cat1
1          comp2         WTA Finals      None  singles  women        cat2
2          comp3    ITF Men Doubles      None  doubles    men        cat3
3          comp4  ITF Women Doubles      None  doubles  women        cat4

In [11]:
query = "SELECT * FROM Competitors"

df = pd.read_sql(query, engine)

df

  competitor_id  competitor_name  country country_code  abbreviation
0            p1   Novak Djokovic   Serbia          SRB   N. Djokovic
1            p2   Carlos Alcaraz    Spain          ESP    C. Alcaraz
2            p3      Iga Swiatek   Poland          POL    I. Swiatek
3            p4  Aryna Sabalenka  Belarus          BLR  A. Sabalenka

In [13]:
query = "SELECT * FROM Competitor_Rankings"

df = pd.read_sql(query, engine)

df

,ranking_id,competitor_id,rank_position,ranking_points,competitions_played
0,1,p1,1,11000,20
1,2,p2,2,9800,18
2,3,p3,1,10500,19
3,4,p4,2,9200,17

In [15]:
import os
print(os.getcwd())

C:\Users\ankit